### ISSUE TITLE
Presets?

### ISSUE THREAD

**Issue by Chaython** [martymcmodding/qUINT#1]
Do you have any presets available? The Reshade overlay doesn't work on Windows 10 1809 for me, in seemingly any game.

**Comment by Chaython** [comment]
The home button did work in Fallout 4 [ I had to long press/ tap repeatedly and it would work [sometimes]. IDK what's up with that.
I tried your FX: 
Bloom = everything was bloomed by default, just a blurry mess
DOF = very intense and dizzying
SSR = looked fine, though everything was reflective, in certain areas it looks really good, however if you look at water the SSR is broken, you can see the shadows/outline of the lake bed rather than any reflections. 
MXAO - not better than the solution already included with Reshade[though the one in Reshade is yours?]; makes some object sharp/black crunched; not a good replacement for traditional AO; a low MXAO pass, with traditional AO does supplement it well.
Don't mind the blown out image this is just using my phone to capture the "artifacts" as screenshots do not capture them.
No SSR/MXAO https://imgur.com/MnEne7c
SSR and MXAO https://i.imgur.com/XqVhstm.jpg
MXAO https://i.imgur.com/Zze3pep.jpg
SSR https://i.imgur.com/MP1s6M2.jpg
As you can see SSR outlines the lake bed, MXAO outlines objects at the bottom of the lake bed

BTW I originally found your FX due to the new Digital Foundry video. https://www.youtube.com/watch?v=NkGvESObKxE
I often enjoy the tech behind games more than the games themselves. This video, definitely doesn't meet the standards I expected from their content. The MXAO has really crunched blacks, and there is tons of artifacts in motion.

**Comment by aaronth07** [comment]
Change the blending mode and fade distance of MXAO and SSR.

Also, https://www.take-a-screenshot.org/

**Comment by Chaython** [comment]
Yes I know how to take screenshots as said it wasn't capturing the reshade; as you can see I took several screenshots
![image](https://user-images.githubusercontent.com/6486343/57263150-e7b85500-702c-11e9-8336-b894bc54fa9a.png)
https://i.imgur.com/4PkkO4N.jpg
Anyways, a restart, and opening fallout 4 again oddly enough screenshot captured it now https://i.imgur.com/SN0PKB8.jpg
Anyways fade out distance, if you're within the distance will still have the artifact...
If you lower it to 0 obviously there would be no artifacts as it wouldn't be rendering the fx...
anyways heading down to ~0.060 this is the result[ https://i.imgur.com/5xA7Mfu.jpg
 ], so artifacting just at the start of the water and the first dip. 0.1 will bring artifacting down to the second - third dip [ https://imgur.com/a/CkQ150C ]
The SSR just really doesn't handle polygonal edges well
Somone was shooting at me so I had to move slightly

Anyways I tested other games, Halo Combat Evolved - SSR renders a transparent hud and everything 600 pixels above the original, nothing looks reflective MXAO the blacks are crunching, with some curves/tonemapping you can make it look decent but most areas are really dark and objects will appear solid black. Also the hud seems to have AO, previous frames AO/depth buffer are rendering during cutscenes/loading screens. AO is rendering overtop of text... 
Halo, during loading screen right before intro cut scene, the autumn, which is transparent here, isn't even rendered until a zoom out/shift later in the cut scene, yet the occlusion layer is already rendered
https://i.imgur.com/XeP9Mi8.png
Very Dark + Reflection artifacts 
![image](https://user-images.githubusercontent.com/6486343/57265119-4680cd00-7033-11e9-89fc-be0f0f0d2e0c.png)
Reflecting Text on the halo ring in the background, and AO rendering above the text
![image](https://user-images.githubusercontent.com/6486343/57265187-a11a2900-7033-11e9-9ca8-0a114a287f60.png)




Ghost Recon Wildlands - SSR makes image darker, but adds some depth to dirt, SSR on the road looks decent but some objects are still overly/illogically reflected such as mossy rock, very heavy performance hit
MXAO - looks equivalent to the SSBC and about the same performance hit there's artifacts where previous frame is slightly rendered [ you can see the depth buffer of the main menu character during the loading screen] you can also see the occlusion appear on top of text/hud. 
Here is a screenshot of assets loading in [player models first, and the AO rendering them over the loading screen. You can see 4 player models, and other assets as they load in, though in game the assets aren't there and they are crouched rather than standing...
https://i.imgur.com/9MvrBLh.jpg



So closing words - This SSR darkens/sharpens image, yet adds a blur to many surfaces or otherwise gives a terrible reflection which is usually very inaccurate, MXAO is competent though has many issues and may be useful in some games, but none that I've found.

Thanks

**Comment by Chaython** [comment]
If you have any good presets for certain games LMK I'd love to try them.
It's been 3 years since he initially showed MXAO, he should've built a good library of presets by now, I'm surprised he doesn't have them in this git.

**Comment by aaronth07** [comment]
Send a screenshot with the Display Depth shader enabled with "Use global preprocessor definitions" (in the shader settings) enabled. Every game handles their depth buffer differently, and Reshade may not have proper access to it. 

And MXAO will show through the HUD, that is just how it works unfortunately. It will also show through effects like smoke and water. Changing the blending mode can help a lot, but you should also change the fade distance as well.

And SSR basically makes every surface like a mirror since Reshade cannot see roughness maps nor can it accurately guess how rough a surface is. You can still adjust how intense the effect is, but it will always reflect everything.

And are you on the latest shaders? Both MXAO and SSR work great for me. MXAO gives me results on par with HBAO/SSDO (SSDO is the better version of SSAO most games use, even if they still call it SSAO), even HBAO+ rarely. SSR also gives me amazing results after some tweaking. Without tweaking it will look like a noisy blurry mess. This goes for MXAO as well, you will need to tweak it to get great results.

**Comment by Chaython** [comment]
the RT shader seems more accurate, doesn't have issues with menus, but in Fallout 4 it flickers and in every game has major ghosting/motion artifacts

**Comment by aaronth07** [comment]
You would get better and quicker help if you commented in the Discord.

**Comment by martymcmodding** [comment]
Not relevant anymore.
