### ISSUE TITLE
qUINT_BLoom.fx throwing Warnings

### ISSUE THREAD

**Issue by Zacam** [martymcmodding/qUINT#11]
ReShade version: 4.5.4.7
DX: D3D9
32bit

Log Output:
11:15:41:021 [14376] | WARN  | Successfully loaded "\reshade-shaders\Shaders\qUINT_bloom.fx" with warnings:
reshade-shaders\Shaders\qUINT_bloom.fx(358, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(367, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(368, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(369, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(370, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(371, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(372, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(373, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(375, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(384, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(385, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(386, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(387, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(388, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(389, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one
reshade-shaders\Shaders\qUINT_bloom.fx(391, 1): warning X4576: 'uv': pixel shader signature does not match vertex shader one

**Comment by Zacam** [comment]
Resolved locally by replacing "TEXCOORD0" in "void PS_" entries with "TEXCOORD"

**Comment by martymcmodding** [comment]
Fixed already.
