### ISSUE TITLE
Bug for GeForce Experience

### ISSUE THREAD

**Issue by ACherepkov1989** [martymcmodding/qUINT#12]
https://github.com/martymcmodding/qUINT/blob/8121afae7b1e487ea33d053a2bbe8892ca359e57/Shaders/qUINT_bloom.fx#L135
Photo of the error
![image](https://user-images.githubusercontent.com/4404804/77919827-571edf00-72a6-11ea-992f-acd8695fdc02.png)

**Comment by martymcmodding** [comment]
Thanks for bringing this to my attention. I'll look into it.

**Comment by martymcmodding** [comment]
Not possible to fix so far, as BUFFER_HEIGHT is not a compile time constant in NvCamera. And I require the last mipmap to reach 1x1 to get a true screen average.
