### ISSUE TITLE
MXAO doesn't work with Bully: Scholarship Edition

### ISSUE THREAD

**Issue by ghost** [martymcmodding/qUINT#13]
https://www.pcgamingwiki.com/wiki/Bully:_Scholarship_Edition

How can I try adjusting the detection? 

Reshade 4.6.1.0, Bully 1.2

**Comment by martymcmodding** [comment]
You probably mean that ReShade doesn't detect the depth buffer - in which case all depth depending effects won't work, not only MXAO. I can't really give game specific support, especially for a game I never used, but experimenting with the settings on the API tab (DX9 for Bully I presume) can help when ReShade didn't take the right buffer but the correct one is in the closer selection.
