### ISSUE TITLE
SSR Fallout New Vegas Transparency Issue

### ISSUE THREAD

**Issue by Leytra** [martymcmodding/qUINT#15]
I was attempting to use these tools to modify Fallout New Vegas's look, and I find that using the Screen-space reflections option, turns my character's drawn weapons transparent, and if I change to third person mode, my character's weapon, which is primarily silver, is not atall reflective.

**Comment by BinToss** [comment]
Get the DisplayDepth shader and post a screenshot of the depth buffer.
Let's see how the game renders the gun to the depth buffer.

**Comment by Leytra** [comment]
Attached is an example of how reshade is rendering everything.
It seems, that how it renders to the depth buffer, is not atall.
![FalloutNV 2020-06-27 12-48-21](https://user-images.githubusercontent.com/52210140/85921502-b1631800-b874-11ea-9633-3dd5de2c62ac.png)
![FalloutNV 2020-06-27 12-48-23](https://user-images.githubusercontent.com/52210140/85921504-b32cdb80-b874-11ea-8b34-e25ef950dde6.png)

**Comment by BinToss** [comment]
The game may have two depth buffers. The second one is likely used for
first-person elements such as the viewmodel (arms, guns) and 3D HUD
elements (power armor, probably).

In ReShade's config overlay, there should be a DirectX tab or something
like that—the last tab. Mess around with the settings there to check if
there is another buffer and verify that buffer shows the viewmodel.

**Comment by Leytra** [comment]
There are only three settings in the Dx9 tab, being fallout NV, there is no 3d hud elements, only the flat ones. 
The three checkboxes in the tab are simple checkboxes, none of which seem to actually do anything more than completely disable all the effects. when changed.

**Comment by martymcmodding** [comment]
Masking static HUD elements has to be done with some UI Mask shader - I'd suggest looking into the official ReShade shader repo for that. Masking objects that aren't visible in the depth buffer however is impossible.
