### ISSUE TITLE
GW2 qUINT shaders issue

### ISSUE THREAD

**Issue by Spawnblade** [martymcmodding/qUINT#16]
The shaders (exclusively qUINT ones, not any of the standard or sweetFX shaders) seem to stop working everytime my character moves, and proceed to not be drawn until I'm standing still.  They work perfectly when not moving.  This is with both DX 9 version of Reshade and DX12, with and without other addons.  Tried about every configuration I could, including attempting earlier builds of qUINT and using Reshade 4.3 (known to have better compat with GW2).  Not sure if I'm doing something wrong or what?

Reshade log here:
https://pastebin.com/UgE74thH

**Comment by EliphasNUIT** [comment]
This is not related to the shaders in this repo. GW2 is an online game and reshade disables the depth buffer, which is needed for MXAO, when it detects a certain amount of network activity. 
My suggestion would be to use a gw2 specific fork of reshade, like GW2Hook or Reshade-GW2. As far as I know, only Reshade-GW2 works with the DX12 addon.

**Comment by martymcmodding** [comment]
Exactly what EliphasNUIT says, ReShade toggles depth buffer off when it detects high network activity of the app you're running it on to prevent cheating. Closing as the solutions have been given.
