### ISSUE TITLE
Using qUINT SSR In Gta 5 

### ISSUE THREAD

**Issue by donxgotti** [martymcmodding/qUINT#17]
maybe its me or the way i installed reshade and quint but for some reason i see black pixels and spots on vehicles in gta 5 is there any way to fix that?

**Comment by BinToss** [comment]
images plz
That would give people a better idea of what you mean.

**Comment by donxgotti** [comment]
> images plz
> That would give people a better idea of what you mean.

![Grand Theft Auto V Screenshot 2020 08 15 - 12 51 13 80](https://user-images.githubusercontent.com/69663263/90317345-c6643b00-def6-11ea-8744-6dffc21e769b.png)
![Grand Theft Auto V Screenshot 2020 08 15 - 12 51 37 97](https://user-images.githubusercontent.com/69663263/90317346-c8c69500-def6-11ea-9cea-fd52d2c8fc5f.png)
