### ISSUE TITLE
Lightroom.fx errors on current GitHub Master builds

### ISSUE THREAD

**Issue by Zacam** [martymcmodding/qUINT#18]
01:13:23:204 [00884] | ERROR | Failed to compile "..\Shaders\qUINT_lightroom.fx":
..\Shaders\qUINT_lightroom.fx(771, 30): error X3691: 'Curves': static variable initial value must be a literal expression
..\Shaders\qUINT_lightroom.fx(804, 30): error X3691: 'Curves': static variable initial value must be a literal expression

Github version built: a1b6450 (Committed on 20/09/20)
Previous working version: 138b1a4 (Committed on 20/09/09)

**Comment by Zacam** [comment]
Not sure if this 'properly' addresses this, but I was able to make it work by removing "static" from in front of lines 771, 772 and lines 804, 805.

**Comment by martymcmodding** [comment]
ReShade had a change recently that gives support for proper static variables but at the same time won't allow static variables to be initialized with anything else than literal expressions (for now, according to crosire). I just use static const out of habit on all variables that will never change, so I just pushed a fix that does the exact same thing as you did, as there's no special requirement for the variable to be static. Thanks for letting me know!
