### ISSUE TITLE
Possible typo in SSR shader?

### ISSUE THREAD

**Issue by ghost** [martymcmodding/qUINT#2]
Line 328: float SSR_FRESNEL_K = 0.0; //matches most surfaces

I'm going to take a leap of faith and say you perhaps meant 0.03-0.04 (F0 of most surfaces). Maybe not. Just thought I'd report it.

**Comment by martymcmodding** [comment]
Yep, that is indeed a typo which I did not intend. Will fix.

**Comment by martymcmodding** [comment]
Done
