### ISSUE TITLE
blue tint with darker blacks on default lightroom values[DX9] 

### ISSUE THREAD

**Issue by ghost** [martymcmodding/qUINT#20]
Hi!
Enabling lightroom in Fallout New Vegas happens to give a blue tint and darker blacks on default values. Tried to nullify it by changing other values, but the image was never the same. I just wonder what would be the cause of that and if there is any workaround or a fix for this issue?

**Comment by martymcmodding** [comment]
DX9 issue, as the coordinates are shifted. The internal LUT is bad anyways, I'll replace it with something better when I have the time.
