### ISSUE TITLE
10-bit backbuffer (contribution)

### ISSUE THREAD

**Issue by ghost** [martymcmodding/qUINT#4]
Hi,
I modified Reshade to be able to utilize 10-bit HDR backbuffers. I've tried it, and unless my eyes are damaged, it works fine.
Here's a link to the commit: https://github.com/MatthewKush/reshade/commit/b85183dd598a6661a14422d565bb0442c1008b80

I'll do a proper pull-request at some point as the repo got messed up and is way behind corsire's somehow. Regardless, it's as simple as that, and when using the format "RGB10A2" in the shaders for MXAO, your new GI, etc. all look better on games that have a 10-bit buffer.

Also, some helpful functions from Microsoft for making manipulating the color-space: https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/Shaders/ShaderUtility.hlsli

Hope I've been helpful. Nice work you're doing.

**Comment by martymcmodding** [comment]
Problem of this is that MXAO stores the SSAO data in the alpha channel. Some games already have rgb10a2 backbuffer and that screwed up MXAO and DOF completely since the stuff in alpha is rounded to 4 distinct values - 2 bit. It's the reason why qUINT has these commontex0 and 1 to ensure im operating in RGBA8. Only the IL texture could benefit from it and since it's blurred anyways, that shouldn't matter.

Which changes did you make in the shaders to leverage the new format?

**Comment by ghost** [comment]
That makes sense, I should have read the shader more carefully, I didn't notice you store the AO data in the alpha.
The changes I made require the C++ code changes I made, and then one would simply use "RGB10A2" in a shader to use it.
I'd send the contribution to the official reshade repository but I seem to remember reading that crosire isn't interested in supporting it, maybe I'm wrong.

**Comment by Mortalitas** [comment]
> That makes sense, I should have read the shader more carefully, I didn't notice you store the AO data in the alpha.
> The changes I made require the C++ code changes I made, and then one would simply use "RGB10A2" in a shader to use it.
> I'd send the contribution to the official reshade repository but I seem to remember reading that crosire isn't interested in supporting it, maybe I'm wrong.

Fairly novel that you'd bring this up when you did:
https://github.com/crosire/reshade/commit/e1a527543a4dd23ba0e5204feed15a8615b5d920

**Comment by ghost** [comment]
@Mortalitas Please forgive me oh perfect one, I did not notice said commit.

**Comment by martymcmodding** [comment]
Well I guess as long as ReShade doesn't have official support, no need to change the files. I do have an eye on it though and will update accordingly when needed.
