### ISSUE TITLE
Conflicting MXAO technique name with default Reshade one

### ISSUE THREAD

**Issue by drandarov-io** [martymcmodding/qUINT#5]
qUINT_mxao.fx and MXAO.fx have the same technique name (MXAO).
This causes the following error (https://reshade.me/forum/troubleshooting/5467-problem-when-2-shaders-with-same-name-are-present)

Not sure if you'd like to address this for convenience sake, since it can cause an unintuitive behavior. If not you can just delete this issue I guess. If it will replace the bundled MXAO in Reshade that it doesn't matter I guess.

**Comment by martymcmodding** [comment]
I'm not sure how to resolve this. Rename either one of the techniques in this repo or the official one and break presets using that version. Rename file to overwrite the one in the official repo  - makes it unclear that they belong together. I hope that people going the extra mile downloading the shaders here know how to resolve this problem.

**Comment by Mortalitas** [comment]
As you may remember Marty, my solution to the issue with the GShade distribution on Final Fantasy XIV was to just append a q to the front of the technique name and have it labelled as ``qMXAO``. Works well enough for us, and there doesn't seem to be much in the way of confusion.

As the filename itself is still standard, that means in the absolute worst case the end user only has to drag the renamed technique back into place and activate it.

**Comment by martymcmodding** [comment]
Well as I said, whatever file you rename will break the config of one file. Since the old MXAO shader has no advantages over the new one, it's best to just replace the old with the new, since ReShade will only look for technique names. I'm not sure if github allows merging 2 different repositories, since I don't want to update MXAO every time in the ReShade repo when I do changes here.

**Comment by martymcmodding** [comment]
Revisiting this, I agree prefixing the techniques is the way to go. Will do this somewhat soon.
