### ISSUE TITLE
MXAO does not respect ReShade 4.5.x RESHADE_DEPTH_INPUT preprocessor definitions

### ISSUE THREAD

**Issue by Expack3** [martymcmodding/qUINT#9]
Tried to use the latest version of MXAO from this repository with the GOG release of Venetica (known there as Venetica: Gold Edition), and noted ReShade's aspect ratio heuristics fail to work correctly. As such, I disabled the heuristics and manually-defined the X and Y scale using the `RESHADE_DEPTH_INPUT_Y_SCALE` and `RESHADE_DEPTH_INPUT_X_SCALE` preprocessor definitions, respectively; manually-setting the offset was unnecessary.

However, after confirming via strictly-visual inspection using the Display Depth shader that my X and Y scale preprocessor definitions were accurate, I then proceeded to disable the Display Depth shader and apply MXAO. As the below images demonstrate, MXAO does not respect my manual tweaking of the depth input scale. Please note that the Display Depth settings which simulate the preprocessor definitions are identical to the ones I've used.

![Release Screenshot 2020 02 26 - 09 07 01 85](https://user-images.githubusercontent.com/5042911/75352965-978ad780-5878-11ea-847e-e06ef1755528.png)
![Release Screenshot 2020 02 26 - 09 07 09 09](https://user-images.githubusercontent.com/5042911/75352967-98bc0480-5878-11ea-9e77-8caeb5d8784a.png)

**Comment by martymcmodding** [comment]
Fixed, see commits :)
